Logs for test basic_kv_view_accept

> SPAWN CLUSTER
spawning cluster of 4 nodes
$ docker network create kvs_0_net_base
  starting container kvs_0_node_0 (ext_port=9000)
$ docker run -d --name kvs_0_node_0 --env NODE_IDENTIFIER=0 -p 9000:8081 kvstore-hw3-test
    attaching container kvs_0_node_0 to base network
$ docker network connect kvs_0_net_base kvs_0_node_0
    inspecting container kvs_0_node_0
    container kvs_0_node_0 spawned, base_net_ip=192.168.97.2
  starting container kvs_0_node_1 (ext_port=9001)
$ docker run -d --name kvs_0_node_1 --env NODE_IDENTIFIER=1 -p 9001:8081 kvstore-hw3-test
    attaching container kvs_0_node_1 to base network
$ docker network connect kvs_0_net_base kvs_0_node_1
    inspecting container kvs_0_node_1
    container kvs_0_node_1 spawned, base_net_ip=192.168.97.3
  starting container kvs_0_node_2 (ext_port=9002)
$ docker run -d --name kvs_0_node_2 --env NODE_IDENTIFIER=2 -p 9002:8081 kvstore-hw3-test
    attaching container kvs_0_node_2 to base network
$ docker network connect kvs_0_net_base kvs_0_node_2
    inspecting container kvs_0_node_2
    container kvs_0_node_2 spawned, base_net_ip=192.168.97.4
  starting container kvs_0_node_3 (ext_port=9003)
$ docker run -d --name kvs_0_node_3 --env NODE_IDENTIFIER=3 -p 9003:8081 kvstore-hw3-test
    attaching container kvs_0_node_3 to base network
$ docker network connect kvs_0_net_base kvs_0_node_3
    inspecting container kvs_0_node_3
    container kvs_0_node_3 spawned, base_net_ip=192.168.97.5
waiting for nodes to come online...
  node kvs_0_node_0 online
  node kvs_0_node_1 online
  node kvs_0_node_2 online
node kvs_0_node_3 is not online: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
  node kvs_0_node_3 online
all nodes online
  - node 0 is up: OK
  - node 1 is up: OK
  - node 2 is up: OK
  - node 3 is up: OK
dumping logs of kvs containers
Dumping logs for container kvs_0_node_3 to file /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_3.log
Successfully wrote logs for container kvs_0_node_3 to /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_3.log
Dumping logs for container kvs_0_node_2 to file /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_2.log
Successfully wrote logs for container kvs_0_node_2 to /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_2.log
Dumping logs for container kvs_0_node_1 to file /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_1.log
Successfully wrote logs for container kvs_0_node_1 to /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_1.log
Dumping logs for container kvs_0_node_0 to file /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_0.log
Successfully wrote logs for container kvs_0_node_0 to /Users/chanwoopark/dev/ucsc/cse138/cse138_assignment4/test_results/2025_03_14_01:42:03/basic/basic_kv_view_accept/kvs_0_node_0.log

> DESTROY CLUSTER
cleaning up group 0
  cleaning up group containers
removing containers ['kvs_0_node_3', 'kvs_0_node_2', 'kvs_0_node_1', 'kvs_0_node_0']
  cleaning up group networks
removing network kvs_0_net_base


âœ— FAILED basic_kv_view_accept: FAIL: 'ClusterNode' object has no attribute 'get_view'
